/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as P100RouteImport } from './routes/p100'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiSfxRouteImport } from './routes/api/sfx'

const P100Route = P100RouteImport.update({
  id: '/p100',
  path: '/p100',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSfxRoute = ApiSfxRouteImport.update({
  id: '/api/sfx',
  path: '/api/sfx',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/p100': typeof P100Route
  '/api/sfx': typeof ApiSfxRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/p100': typeof P100Route
  '/api/sfx': typeof ApiSfxRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/p100': typeof P100Route
  '/api/sfx': typeof ApiSfxRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/p100' | '/api/sfx'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/p100' | '/api/sfx'
  id: '__root__' | '/' | '/p100' | '/api/sfx'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  P100Route: typeof P100Route
  ApiSfxRoute: typeof ApiSfxRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/p100': {
      id: '/p100'
      path: '/p100'
      fullPath: '/p100'
      preLoaderRoute: typeof P100RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sfx': {
      id: '/api/sfx'
      path: '/api/sfx'
      fullPath: '/api/sfx'
      preLoaderRoute: typeof ApiSfxRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  P100Route: P100Route,
  ApiSfxRoute: ApiSfxRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
